I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 45, in script
    call screen chooseLocMove
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Screen chooseLocMove is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 45, in script
    call screen chooseLocMove
  File "D:\Programms\renpy-8.3.3-sdk\renpy\ast.py", line 1974, in execute
    self.call("execute")
  File "D:\Programms\renpy-8.3.3-sdk\renpy\ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\Programms\renpy-8.3.3-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "D:\Programms\renpy-8.3.3-sdk\renpy\exports\statementexports.py", line 331, in call_screen
    renpy.exports.show_screen(_screen_name, *args, _transient=True, **kwargs)
  File "D:\Programms\renpy-8.3.3-sdk\renpy\display\screen.py", line 1327, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen chooseLocMove is not known.


Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
Novel 1.0
Mon Dec 16 21:41:23 2024
